# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 03:02
from __future__ import unicode_literals

import account.fields
import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', account.fields.AvatarImageField(default='defaultprofile.png', upload_to=account.models.manage_upload)),
                ('description', models.TextField(max_length=200)),
                ('actual_job', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_change_profile', 'Can edit the profile'),),
            },
        ),
    ]
