# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180221_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actual_job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
