# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180314_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
