# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 11:45
from __future__ import unicode_literals

import account.fields
import account.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180615_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=account.fields.AvatarImageField(blank=True, upload_to=account.models.manage_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pcd', 'jpg', 'bw', 'h5', 'gif', 'ppm', 'pgm', 'j2k', 'dcx', 'pcx', 'blp', 'bufr', 'gbr', 'xpm', 'pxr', 'msp', 'jpe', 'jpc', 'jp2', 'xbm', 'mpg', 'icns', 'jpeg', 'ftc', 'ftu', 'ras', 'fit', 'eps', 'fits', 'ico', 'bmp', 'j2c', 'png', 'sgi', 'iim', 'tiff', 'flc', 'rgba', 'tif', 'emf', 'dds', 'rgb', 'palm', 'pbm', 'ps', 'fli', 'mpeg', 'tga', 'pdf', 'grib', 'wmf', 'jpx', 'mpo', 'jfif', 'jpf', 'psd', 'hdf', 'cur', 'im'])]),
        ),
    ]
