# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 12:36
from __future__ import unicode_literals

import account.fields
import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180615_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=account.fields.AvatarImageField(blank=True, upload_to=account.models.manage_upload),
        ),
    ]
