version: '3'

services:
  db:
    build: ./db
    image: matt115/postgres_project
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: ./web
    image: matt115/django_project
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./project/:/project/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    restart: on-failure

