# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0005_auto_20180612_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(),
        ),
    ]
