# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0009_auto_20180612_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'permissions': (('can_open_thread', 'Can open a thread'),)},
        ),
    ]
