# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0011_auto_20180612_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'permissions': (('can_open_threads', 'Can open a thread'),)},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
    ]
