# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('PEN', 'pending')], default='PEN', max_length=3)),
                ('label', models.CharField(default='', max_length=20, unique=True)),
                ('tile', models.CharField(default='', max_length=70)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status_date', models.DateTimeField(auto_now=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_sent', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='to',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterUniqueTogether(
            name='socialrequest',
            unique_together=set([('by', 'to')]),
        ),
    ]
