# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0002_auto_20180504_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrequest',
            name='label',
            field=models.CharField(default='', max_length=20),
        ),
    ]
