# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0002_auto_20180524_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrequest',
            name='tile',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
