# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marathon', '0003_auto_20180513_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrequest',
            name='label',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='socialrequest',
            unique_together=set([('by', 'to', 'label')]),
        ),
    ]
