# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 12:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0004_auto_20180513_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialrequest',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
