# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20180314_0937'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_sended', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Profile')),
                ('profiles', models.ManyToManyField(related_name='projectpages', to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='inviterequest',
            name='project_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectpager.ProjectPage'),
        ),
        migrations.AddField(
            model_name='inviterequest',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inviterequest',
            unique_together=set([('by', 'to')]),
        ),
    ]
