# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Profile'),
        ),
    ]
