# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='users',
            field=models.ManyToManyField(related_name='projectpages', to=settings.AUTH_USER_MODEL),
        ),
    ]
