# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0002_auto_20180524_0357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inviterequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='by',
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='project_page',
        ),
        migrations.RemoveField(
            model_name='inviterequest',
            name='to',
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'permissions': (('can_post_discussions', 'Can post new discussions to page.'),)},
        ),
        migrations.DeleteModel(
            name='InviteRequest',
        ),
    ]
