# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0002_auto_20180503_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
