# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180607_1331'),
        ('projectpager', '0003_auto_20180526_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='projectpager.ProjectPage')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projectpager.Thread'),
        ),
        migrations.AddField(
            model_name='message',
            name='posted_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
