# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0004_auto_20180612_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='hey', max_length=150),
            preserve_default=False,
        ),
    ]
