# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0007_auto_20180612_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
