# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0008_auto_20180612_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={},
        ),
    ]
