# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpager', '0012_auto_20180612_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='name',
            new_name='_name',
        ),
    ]
