# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 13:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20180314_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('PEN', 'pending')], default='PEN', max_length=3)),
                ('label', models.CharField(max_length=20)),
                ('tile', models.CharField(default='', max_length=70)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status_date', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_sent', to='account.Profile')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marathon_received', to='account.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='socialrequest',
            unique_together=set([('by', 'to', 'label')]),
        ),
    ]
