# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0003_auto_20180524_1417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialrequest',
            unique_together=set([]),
        ),
    ]
