# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0004_auto_20180612_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialrequest',
            name='status',
            field=models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('PEN', 'pending'), ('DIS', 'disabled')], default='PEN', max_length=3),
        ),
    ]
