# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SkillData',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(help_text='codename for the skill', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiller.SkillData'),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiller.Skill'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('user', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='confirmation',
            unique_together=set([('skill', 'to', 'by')]),
        ),
    ]
