# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilldata',
            name='description',
            field=models.TextField(blank=True, help_text='Describe your eventual experience or let blank', max_length=400),
        ),
    ]
