# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilldata',
            name='description',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Describe your eventual experience or let blank', max_length=400),
        ),
    ]
