# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiller', '0002_skilldata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldata',
            name='_codename',
            field=models.CharField(help_text='codename for the skill', max_length=20, unique=True, verbose_name='skill_name'),
        ),
    ]
