# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiller', '0004_auto_20180409_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldata',
            name='_codename',
            field=models.CharField(db_column='skill name', help_text='codename for the skill', max_length=20, unique=True),
        ),
    ]
