# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skiller', '0006_auto_20180425_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
