# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommander', '0002_auto_20180613_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('v', 'user visited')], max_length=1),
        ),
    ]
