# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_auto_20180429_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-_sent_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='_message',
        ),
    ]
