# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 14:30
from __future__ import unicode_literals

from django.db import migrations
import messanger.models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_auto_20180501_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=messanger.models.FormattedTextField(max_length=200),
        ),
    ]
