# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20180314_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Profile')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.Profile')),
            ],
        ),
    ]
