# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendship', '0003_friendshiprequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set([('by', 'to')]),
        ),
    ]
