# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180218_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_change_profile', 'Can edit the profile'),)},
        ),
    ]
