# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 13:12
from __future__ import unicode_literals

import account.fields
import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180219_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=account.fields.AvatarImageField(default='defaultprofile.png', upload_to=account.models.manage_upload),
        ),
    ]
