# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 09:37
from __future__ import unicode_literals

import account.fields
import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180314_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=account.fields.AvatarImageField(upload_to=account.models.manage_upload),
        ),
    ]
