# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180606_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_img',
            new_name='img',
        ),
    ]
