# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 11:45
from __future__ import unicode_literals

import account.fields
import account.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180607_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=account.fields.AvatarImageField(blank=True, upload_to=account.models.manage_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wmf', 'cur', 'bw', 'fits', 'xbm', 'tiff', 'xpm', 'rgba', 'fit', 'gif', 'grib', 'ico', 'pxr', 'jpg', 'pbm', 'emf', 'dds', 'iim', 'hdf', 'tif', 'im', 'jp2', 'pdf', 'dcx', 'mpg', 'ppm', 'ps', 'icns', 'pgm', 'gbr', 'pcd', 'ftu', 'h5', 'jpeg', 'fli', 'jfif', 'msp', 'rgb', 'blp', 'pcx', 'jpf', 'ras', 'jpc', 'bufr', 'mpo', 'psd', 'j2k', 'j2c', 'bmp', 'jpx', 'eps', 'mpeg', 'palm', 'ftc', 'flc', 'png', 'jpe', 'sgi', 'tga'])]),
        ),
    ]
