# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 12:32
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180615_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, upload_to=account.models.manage_upload),
        ),
    ]
