# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='_sent_at',
        ),
    ]
