# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import skiller.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_auto_20180314_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SkillData',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('_codename', models.CharField(db_column='skill name', help_text='codename for the skill', max_length=20, unique=True, validators=[skiller.validators.validate_invalid_chars])),
                ('description', models.TextField(blank=True, help_text='Describe your eventual experience or let blank', max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiller.SkillData'),
        ),
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skiller.Skill'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('profile', 'data')]),
        ),
        migrations.AlterUniqueTogether(
            name='confirmation',
            unique_together=set([('skill', 'to', 'by')]),
        ),
    ]
